# Generated by Django 3.2 on 2023-09-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0002_auto_20230905_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
