# Generated by Django 3.2 on 2023-09-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0003_alter_recipes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
