# Generated by Django 3.2 on 2023-09-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0004_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='description',
            field=models.TextField(default=None, max_length=150),
        ),
    ]
