# Generated by Django 3.2 on 2023-09-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0006_alter_recipes_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='description',
        ),
    ]
