# Generated by Django 3.2 on 2023-09-05 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0008_recipes_recipe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='recipe_description',
        ),
        migrations.AddField(
            model_name='recipes',
            name='recipe_desc',
            field=models.CharField(blank=True, max_length=30),
            preserve_default=False,
        ),
    ]
