# Generated by Django 3.2 on 2023-09-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0009_auto_20230905_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='recipe_desc',
        ),
    ]
