# Generated by Django 3.2 on 2023-09-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0011_alter_recipes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
