# Generated by Django 3.2 on 2023-09-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0013_auto_20230905_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_desc',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
