# Generated by Django 3.2 on 2023-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0014_recipes_recipe_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_desc',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
