# Generated by Django 3.2 on 2023-09-08 14:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0015_auto_20230905_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
