# Generated by Django 3.2 on 2023-09-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0016_recipes_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_story',
            field=models.TextField(blank=True),
        ),
    ]
