# Generated by Django 3.2 on 2023-09-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0017_recipes_recipe_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients_list',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='methods_list',
            field=models.TextField(blank=True),
        ),
    ]
