# Generated by Django 3.2 on 2023-09-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0019_alter_recipes_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='slug',
        ),
    ]
