# Generated by Django 3.2 on 2023-09-17 08:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0020_remove_recipes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='ingredients_list',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='methods_list',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_story',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
