# Generated by Django 3.2 on 2023-09-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0021_auto_20230917_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
