# Generated by Django 3.2 on 2023-09-19 11:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0023_alter_recipes_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
