# Generated by Django 3.2 on 2023-09-21 17:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0025_alter_recipes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
