# Generated by Django 3.2 on 2023-09-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktake', '0026_alter_recipes_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
